added grid
sashameniakin/personal-website pull request #3
Opened 2022-10-14 07:02 UTC by sashameniakin

added grid and some updates

2022-10-14 13:57 UTC, actyralf requested changes
Well done!
I left a few comments, please take a look. I also recognized that you are using links containing only images and no text. Please use ària-label` in this case to make screen readers aware of the purpose of your links.

2022-10-14 13:57 UTC, actyralf commented on index.html
>          src="/Users/oleksandrmeniakin/Downloads/image_6487327.JPG"
please don't use images outside of your project folder, they cannot be controlled by git/github.
a common folder structure would be:

```

/assets
   /images
      image1.jpg
      image2.jpg
   /fonts
      font1.ttf
      etc...
```

2022-10-14 13:57 UTC, actyralf commented on style.css
>  @import url(components/buttons.css);
please watch the order of your `@import` directives: you should have one file **only with imports** (no css rules in it!) that controls the order. Then you should import reset / globals first and more specific files like components afterwards.

2022-10-17 07:10 UTC, sashameniakin commented on index.html
>          src="/Users/oleksandrmeniakin/Downloads/image_6487327.JPG"
thank you for the comment, i will realize it in the next commit!

2022-10-17 07:10 UTC, merged